apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{.Values.name }}
    kubernetes.io/part-of: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.externalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ .Values.name }}